name: 'i18n tag audit'
description: 'Record i18n keys that are not defined per file in next-i18n-next'
inputs:
  grepList:  # string list from git grep
    description: 'output from git grep as manipulated in prior steps'
    required: true
    default: ''
  localeDir: # directory of the language folders
    description: 'locales dir in the application'
    required: true
    default: 'public/locales'
outputs:
  missingObject: # id of output
    description: 'The top level object containing file names and missing keys'
runs:
  using: 'node12'
  main: 'dist/index.js'
